# Generated by Django 4.1.4 on 2023-02-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_artworkcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcomment',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.artwork'),
        ),
    ]
