# Generated by Django 4.1.4 on 2022-12-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_artwork_genre_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='genre_title',
        ),
    ]
