# Generated by Django 4.1.3 on 2022-12-29 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('store', '0004_remove_artwork_genre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='genre.genre'),
            preserve_default=False,
        ),
    ]
