# Generated by Django 4.1.4 on 2023-02-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userlikedartwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcomment',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
