# Generated by Django 4.1.4 on 2023-02-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_artworkcomment_isavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkcomment',
            name='isAvailable',
        ),
        migrations.AddField(
            model_name='artwork',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
