# Generated by Django 4.1.4 on 2023-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_artworkcomment_isavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
