# Generated by Django 4.1.4 on 2023-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auction_bid_auction_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='starting_price',
            field=models.IntegerField(default=0),
        ),
    ]
