# Generated by Django 4.1.4 on 2023-03-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
