# Generated by Django 4.1.4 on 2023-04-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auction_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
