# Generated by Django 4.1.4 on 2023-02-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
