# Generated by Django 4.1.4 on 2023-03-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auction_end_time'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.artwork'),
            preserve_default=False,
        ),
    ]
