# Generated by Django 4.1.4 on 2023-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_artportfolio_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artportfolio',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
